"""Add phone and address to user

Revision ID: 04963581bef0
Revises: 3580a219846a
Create Date: 2025-08-05 09:41:25.257208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04963581bef0'
down_revision = '3580a219846a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
